/*
# Save UX Redesign — short codes, search, file names

## Purpose
Enhances the saved_items table to support the redesigned Save UX:
shorter save codes, full-text search across caption/filename/code/mime,
and a dedicated file_name column for accurate media type preservation.

## Changes to existing tables

### saved_items (modified)
- ADD COLUMN file_name text — original filename of the saved media.
  Stored separately from caption so the dashboard and search can show
  the real filename even when the caption is a generated block.
  Nullable: existing rows (forward saves without filename) keep NULL.
- ADD COLUMN short_code text UNIQUE — new compact save code
  (e.g. "S391", "A82"). Nullable: existing rows keep NULL and remain
  addressable by their original save_code. New saves get a short_code.
  Both save_code (legacy SV-NNNNNN) and short_code (new SNNN) are UNIQUE;
  lookups try short_code first, then fall back to save_code for backward
  compatibility.

## Indexes (new)
- idx_saved_items_short_code on saved_items (short_code) — fast lookup
  by the new compact code.
- idx_saved_items_owner_created on saved_items (owner_id, created_at DESC)
  — composite index for .list (recent items per owner).
- trigram indexes on caption, file_name, save_code, short_code, mime_type
  for fast ILIKE / similarity search used by .find. Requires pg_trgm.

## Extensions
- CREATE EXTENSION IF NOT EXISTS pg_trgm — required for trigram search
  indexes (gin_trgm_ops) used by .find.

## Security
- No RLS policy changes. Existing SELECT-only anon/authenticated policies
  remain in effect. All writes go through the backend service-role key.
- No data is dropped or modified. Existing rows are untouched.

## Important notes
1. The save_code column and all existing SV-NNNNNN codes are preserved.
   Old .preview/.send/.retrieve commands keep working because the DB
   layer falls back to save_code when short_code lookup fails.
2. file_name is nullable so the migration is safe for all existing rows.
3. short_code is nullable + UNIQUE so existing rows (NULL) do not violate
   the constraint, and new rows get a unique short code generated by the
   backend (which checks for collisions before insert).
4. pg_trgm is enabled with IF NOT EXISTS — safe to re-run.
*/

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE saved_items
    ADD COLUMN IF NOT EXISTS file_name text,
    ADD COLUMN IF NOT EXISTS short_code text;

DROP INDEX IF EXISTS idx_saved_items_short_code;
CREATE UNIQUE INDEX IF NOT EXISTS idx_saved_items_short_code
    ON saved_items (short_code) WHERE short_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_saved_items_owner_created
    ON saved_items (owner_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_saved_items_caption_trgm
    ON saved_items USING gin (caption gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_saved_items_file_name_trgm
    ON saved_items USING gin (file_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_saved_items_save_code_trgm
    ON saved_items USING gin (save_code gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_saved_items_short_code_trgm
    ON saved_items USING gin (short_code gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_saved_items_mime_trgm
    ON saved_items USING gin (mime_type gin_trgm_ops);
